version: '3.4'

services:
  wdash:
    image: wdash
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        WDB_URL: "http://localhost:5002"
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
