version: '3.4'

services:
  wdash:
    image: wdash
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./secrets/wdb.json:/usr/src/app/src/wdb.json
