version: '3.4'

services:
  wdash:
    image: ghcr.io/tanmoysg/wunderdash:latest
    environment:
      NODE_ENV: production
      WDB_URL: http://localhost:5002
    ports:
      - 3000:3000
